apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-er5y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-er5y
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-er5y
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-er5y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-er5y
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ycfh-tenant/rhtap-demo-app/hacbs-test-project-er5y@sha256:5c586d8c00834802dfb648b70c32ed13edb82da8e1e88e059d77a42dbf267cc5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
